version: '3.1'

services:

  db:
    container_name: gh-analysis-db
    image: postgres:13.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: github
      POSTGRES_DB: github
      POSTGRES_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/postgresql/data
      - type: bind
        source: ./data
        read_only: true
        target: /tmp/input

volumes:
  dbdata:
